=== Sai04-S/wad-assignment-3-2845-Q1/student.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (SID,SName,Age,Address,DOB)>
<!ELEMENT SID (#PCDATA)>
<!ELEMENT SName (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT DOB (#PCDATA)>

=== Sai04-S/wad-assignment-3-2845-Q1/student.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="student.css"?>
<!DOCTYPE students SYSTEM "student.dtd">
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="student.xsd">
    <student>
        <SID>101</SID>
        <SName>Sai</SName>
        <Age>20</Age>
        <Address>Hyderabad</Address>
        <DOB>2005-01-10</DOB>
    </student>
    <student>
        <SID>102</SID>
        <SName>Rahul</SName>
        <Age>21</Age>
        <Address>Vizag</Address>
        <DOB>2004-02-15</DOB>
    </student>
    <student>
        <SID>103</SID>
        <SName>Priya</SName>
        <Age>19</Age>
        <Address>Vijayawada</Address>
        <DOB>2006-05-12</DOB>
    </student>
    <student>
        <SID>104</SID>
        <SName>Kiran</SName>
        <Age>22</Age>
        <Address>Guntur</Address>
        <DOB>2003-07-20</DOB>
    </student>
    <student>
        <SID>105</SID>
        <SName>Anjali</SName>
        <Age>20</Age>
        <Address>Nellore</Address>
        <DOB>2005-11-25</DOB>
    </student>
</students>
